export const listfriday = [
  { time: "13:00", action: "friday" },
  { time: "14:00", action: "friday" },
  { time: "15:00", action: "friday" },
  { time: "16:00", action: "friday" },
  { time: "17:00", action: "friday" },
  { time: "18:00", action: "friday" },
  { time: "19:00", action: "friday" },
  { time: "20:00", action: "friday" },
  { time: "21:00", action: "friday" },
  { time: "22:00", action: "friday" },
  { time: "23:00", action: "friday" },
  { time: "24:00", action: "friday" },
  { time: "01:00", action: "friday" },
  { time: "02:00", action: "friday" },
];

export const listsaturday = [
  { time: "13:00", action: "saturday" },
  { time: "14:00", action: "saturday" },
  { time: "15:00", action: "saturday" },
  { time: "16:00", action: "saturday" },
  { time: "17:00", action: "saturday" },
  { time: "18:00", action: "saturday" },
  { time: "19:00", action: "saturday" },
  { time: "20:00", action: "saturday" },
  { time: "21:00", action: "saturday" },
  { time: "22:00", action: "saturday" },
  { time: "23:00", action: "saturday" },
  { time: "24:00", action: "saturday" },
  { time: "01:00", action: "saturday" },
  { time: "02:00", action: "saturday" },
];
export const listsunday = [
  { time: "13:00", action: "sunday" },
  { time: "14:00", action: "sunday" },
  { time: "15:00", action: "sunday" },
  { time: "16:00", action: "sunday" },
  { time: "17:00", action: "sunday" },
  { time: "18:00", action: "sunday" },
  { time: "19:00", action: "sunday" },
  { time: "20:00", action: "sunday" },
  { time: "21:00", action: "sunday" },
  { time: "22:00", action: "sunday" },
  { time: "23:00", action: "sunday" },
  { time: "24:00", action: "sunday" },
  { time: "01:00", action: "sunday" },
  { time: "02:00", action: "sunday" },
];
